#if !canImport(ObjectiveC)
import XCTest

extension AsyncOperationResultTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AsyncOperationResultTests = [
        ("testBasicErrorUsage", testBasicErrorUsage),
        ("testBasicSuccessUsage", testBasicSuccessUsage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AsyncOperationResultTests.__allTests__AsyncOperationResultTests),
    ]
}
#endif
